### ISSUE TITLE
Upgrading Guzzle dependency

### ISSUE THREAD

**Issue by andrei-dascalu** [TinEye/tineye-api-php#4]
Hello,

I am wondering whether you would considering updating the Guzzle dependency to 7 (or make it compatible with)?

The main effect of this would be that the minimum supported version of PHP would become 7.2 (depending on your support strategy this may or may not be a problem though, since PHP 7.3 is also approaching its EOL this year).

I've created a merge request to this effect, perhaps it can be helpful.

Cheers

**Comment by rhettlunn** [comment]
Thanks for the merge request! This has been merged in and released in 1.1.0:
https://github.com/TinEye/tineye-api-php/releases/tag/1.1.0

https://github.com/TinEye/tineye-api-php/commit/c147b525bde9353ee2b09721d20cc635e78fa790
